spring:
  application:
    name: samvada

#  Data Behaviour
  data:
    mongodb:
      auto-index-creation: true
  #  MongoDB Configuration
  mongodb:
    uri: mongodb://roo:password%40123@localhost:27017/samvada_db?authSource=admin