spring:
  application:
    name: samvada

#  Data Behaviour
  data:
    mongodb:
      auto-index-creation: true

#    redis:
#      url: redis://${REDIS_USR:}:${REDIS_PW:password123}@localhost:6379/0

  #  MongoDB Configuration
  mongodb:
    uri: mongodb+srv://${MONGO_USER}:${MONGO_PWD}@${MONGO_HOST}/samvada_db?retryWrites=true&w=majority&appName=tharka-cluster


jwt:
  secret: ${JWT_SECRET:this_is_just_for_local_dev_testing_12345}

app:
  security:
    cookie-secure: false

#logging:
#  level:
#    org:
#      springframework:
#        security:
#          authentication:
#            dao:
#              DaoAuthenticationProvider: DEBUG
#          web:
#            authentication:
#              www:
#                BasicAuthenticationFilter: DEBUG