spring:
  application:
    name: samvada

#  Data Behaviour
  data:
    mongodb:
      auto-index-creation: true
  #  MongoDB Configuration
  mongodb:
    uri: mongodb://root:password%40123@127.0.0.1:27017/samvada_db?authSource=admin
jwt:
  secret: ${JWT_SECRET:this_is_just_for_local_dev_testing_12345}
#logging:
#  level:
#    org:
#      springframework:
#        security:
#          authentication:
#            dao:
#              DaoAuthenticationProvider: DEBUG
#          web:
#            authentication:
#              www:
#                BasicAuthenticationFilter: DEBUG